sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.4.0
before_install: gem install bundler -v 1.13.3
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
